use_frameworks!

platform :ios, '9.0'

target 'XmlToXibRuntime_Example' do
  pod 'XmlToXibRuntime', :path => '../'

  target 'XmlToXibRuntime_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
